-- DATA CLEANING
USE WORLD_LAYOFFS;
SELECT * FROM LAYOFFS;
SELECT * FROM LAYOFFS_STAGING;


CREATE TABLE LAYOFFS_STAGING
LIKE LAYOFFS;
INSERT LAYOFFS_STAGING
SELECT * FROM LAYOFFS;

WITH DUPLICATE_CTE AS 
(
SELECT *,
ROW_NUMBER() OVER(PARTITION BY  COMPANY,LOCATION,INDUSTRY,TOTAL_LAID_OFF,PERCENTAGE_LAID_OFF,'DATE',STAGE,COUNTRY,FUNDS_RAISED_MILLIONS) AS ROW_NUM
FROM LAYOFFS_STAGING
)
SELECT * FROM DUPLICATE_CTE WHERE ROW_NUM>1;

CREATE TABLE `layoffs_staging2` (
  `company` text,
  `location` text,
  `industry` text,
  `total_laid_off` int DEFAULT NULL,
  `percentage_laid_off` text,
  `date` text,
  `stage` text,
  `country` text,
  `funds_raised_millions` int DEFAULT NULL,
   `row_num` int
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

SELECT * FROM LAYOFFS_STAGING2;

INSERT INTO LAYOFFS_STAGING2
SELECT *,
ROW_NUMBER() OVER(PARTITION BY  COMPANY,LOCATION,INDUSTRY,TOTAL_LAID_OFF,PERCENTAGE_LAID_OFF,'DATE',STAGE,COUNTRY,FUNDS_RAISED_MILLIONS) AS ROW_NUM
FROM LAYOFFS_STAGING;

SELECT * FROM LAYOFFS_STAGING2 WHERE ROW_NUM>1;

DELETE FROM LAYOFFS_STAGING2 WHERE ROW_NUM>1;

SELECT * FROM LAYOFFS_STAGING2;

SELECT COMPANY FROM LAYOFFS_STAGING2;

SELECT COMPANY,TRIM(COMPANY) FROM LAYOFFS_STAGING2;

UPDATE LAYOFFS_STAGING2
SET COMPANY = TRIM(COMPANY);

SELECT distinct(INDUSTRY) FROM LAYOFFS_STAGING2 ORDER BY INDUSTRY  ;

SELECT * FROM LAYOFFS_STAGING2 WHERE INDUSTRY LIKE "%CRYPTO%";
UPDATE LAYOFFS_STAGING2 SET INDUSTRY='CRYPTO' WHERE INDUSTRY LIKE "CRYPTO%";

SELECT distinct(LOCATION) FROM LAYOFFS_STAGING2 ORDER BY LOCATION ;

SELECT distinct(COUNTRY) FROM LAYOFFS_STAGING2 ORDER BY COUNTRY;
SELECT * FROM LAYOFFS_STAGING2 WHERE COUNTRY LIKE "United States%"; 
UPDATE LAYOFFS_STAGING2 SET COUNTRY="United States" WHERE COUNTRY LIKE "United States%";

SELECT DATE FROM LAYOFFS_STAGING2 ORDER BY DATE ;

select DATE,
STR_TO_DATE(DATE,'%m/%d/%Y')
FROM LAYOFFS_STAGING2;

UPDATE LAYOFFS_STAGING2
SET DATE=STR_TO_DATE(DATE,'%m/%d/%Y');

ALTER TABLE LAYOFFS_STAGING2 
modify column DATE date;

SELECT * FROM LAYOFFS_STAGING2;

select T1.INDUSTRY,T2.INDUSTRY
FROM LAYOFFS_STAGING2 T1
JOIN LAYOFFS_STAGING2 T2 
ON T1.COMPANY = T2.COMPANY
WHERE (	T1.INDUSTRY IS NULL OR T1.INDUSTRY ="")
AND T2.INDUSTRY IS NOT NULL;

UPDATE LAYOFFS_STAGING2
SET INDUSTRY = NULL
WHERE INDUSTRY ="";			

UPDATE LAYOFFS_STAGING2 T1
JOIN LAYOFFS_STAGING2 T2
ON T1.COMPANY=T2.COMPANY
SET T1.INDUSTRY = T2.INDUSTRY
WHERE T1.INDUSTRY IS NULL
AND T2.INDUSTRY IS NOT NULL;

SELECT * FROM LAYOFFS_STAGING2 WHERE COMPANY = "AIRBNB";
SELECT * FROM LAYOFFS_STAGING2  ;

SELECT COMPANY,INDUSTRY FROM LAYOFFS_STAGING2 WHERE INDUSTRY IS NULL OR "";

SELECT *
FROM LAYOFFS_STAGING2 
WHERE percentage_laid_off IS NULL 
AND total_laid_off IS NULL  ;

DELETE
FROM LAYOFFS_STAGING2 
WHERE percentage_laid_off IS NULL 
AND total_laid_off IS NULL  ;

SELECT * FROM LAYOFFS_STAGING2 WHERE total_laid_off IS NULL ;
SELECT * FROM LAYOFFS_STAGING2 WHERE percentage_laid_off IS NULL ;

 ALTER  TABLE LAYOFFS_STAGING2 
 DROP COLUMN ROW_NUM;
 
 SELECT * FROM LAYOFFS_STAGING2;


