use WORLD_LAYOFFS;
SELECT * FROM LAYOFFS_STAGING2;

SELECT * 
FROM LAYOFFS_STAGING2 
WHERE percentage_laid_off =1
ORDER BY 9 DESC ;

SELECT COMPANY , SUM(total_laid_off)
FROM LAYOFFS_STAGING2 
GROUP BY COMPANY
ORDER BY 2 DESC ;

SELECT MIN(DATE),MAX(DATE)
FROM LAYOFFS_STAGING2 ;

SELECT COUNTRY , SUM(total_laid_off)
FROM LAYOFFS_STAGING2 
GROUP BY COUNTRY
ORDER BY 2 DESC ;

SELECT YEAR(DATE) , SUM(total_laid_off)
FROM LAYOFFS_STAGING2 
GROUP BY YEAR(DATE)
ORDER BY 1 DESC ;

SELECT substring(DATE,6,2) MONTH ,SUM(total_laid_off)
FROM LAYOFFS_STAGING2
GROUP BY MONTH;

SELECT substring(DATE,1,7) MONTH ,SUM(total_laid_off)
FROM LAYOFFS_STAGING2
WHERE substring(DATE,1,7) IS NOT NULL
GROUP BY MONTH
ORDER BY 1;

WITH ROLLING_TOTAL AS
(SELECT substring(DATE,1,7) MONTH ,SUM(total_laid_off) AS TOTAL_OFF
FROM LAYOFFS_STAGING2
WHERE substring(DATE,1,7) IS NOT NULL
GROUP BY MONTH
ORDER BY MONTH
)
SELECT MONTH ,TOTAL_OFF,SUM(TOTAL_OFF) OVER(ORDER BY MONTH) AS ROLLING_TOTAL
FROM ROLLING_TOTAL;

SELECT COMPANY , YEAR(DATE) , SUM(TOTAL_LAID_OFF)
FROM LAYOFFS_STAGING2
GROUP BY COMPANY,YEAR(DATE)
ORDER BY 3 DESC;

WITH COMPANY_YEAR (COMPANY , YEARS , TOTAL_LAID_OFF) AS
(
SELECT COMPANY , YEAR(DATE) , SUM(TOTAL_LAID_OFF)
FROM LAYOFFS_STAGING2
GROUP BY COMPANY,YEAR(DATE)
ORDER BY 3 DESC
),COMPANY_YEARS_RANK AS
(
SELECT *,rank() OVER (PARTITION BY YEARS ORDER BY TOTAL_LAID_OFF DESC) AS RANKS
 FROM COMPANY_YEAR
 WHERE YEARS IS NOT NULL AND TOTAL_LAID_OFF IS NOT NULL
 )
 SELECT * FROM COMPANY_YEARS_RANK
 WHERE RANKS <=5;






